package com.company.protos;

public class Question {
}
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/aisera/proto/messages.proto

package com.aisera.common;

/**
 * Protobuf type {@code Question}
 */
public  final class Question extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Question)
        QuestionOrBuilder {
    // Use Question.newBuilder() to construct.
    private Question(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }
    private Question() {
        text_ = "";
        quads_ = java.util.Collections.emptyList();
        originalText_ = "";
        entities_ = java.util.Collections.emptyList();
        assetDesc_ = "";
        spellCheckedText_ = "";
        nodes_ = java.util.Collections.emptyList();
        sentimentContentCached_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Question(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        text_ = s;
                        break;
                    }
                    case 18: {
                        if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                            quads_ = new java.util.ArrayList<com.aisera.common.Quad>();
                            mutable_bitField0_ |= 0x00000002;
                        }
                        quads_.add(
                                input.readMessage(com.aisera.common.Quad.parser(), extensionRegistry));
                        break;
                    }
                    case 26: {
                        com.aisera.common.Sentence.Builder subBuilder = null;
                        if (sentence_ != null) {
                            subBuilder = sentence_.toBuilder();
                        }
                        sentence_ = input.readMessage(com.aisera.common.Sentence.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(sentence_);
                            sentence_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 34: {
                        java.lang.String s = input.readStringRequireUtf8();

                        originalText_ = s;
                        break;
                    }
                    case 42: {
                        if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                            entities_ = new java.util.ArrayList<com.aisera.common.KGEntity>();
                            mutable_bitField0_ |= 0x00000010;
                        }
                        entities_.add(
                                input.readMessage(com.aisera.common.KGEntity.parser(), extensionRegistry));
                        break;
                    }
                    case 50: {
                        java.lang.String s = input.readStringRequireUtf8();

                        assetDesc_ = s;
                        break;
                    }
                    case 58: {
                        java.lang.String s = input.readStringRequireUtf8();

                        spellCheckedText_ = s;
                        break;
                    }
                    case 66: {
                        if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                            nodes_ = new java.util.ArrayList<com.aisera.common.KGNode>();
                            mutable_bitField0_ |= 0x00000080;
                        }
                        nodes_.add(
                                input.readMessage(com.aisera.common.KGNode.parser(), extensionRegistry));
                        break;
                    }
                    case 74: {
                        com.aisera.common.Content.Builder subBuilder = null;
                        if (kgnerContent_ != null) {
                            subBuilder = kgnerContent_.toBuilder();
                        }
                        kgnerContent_ = input.readMessage(com.aisera.common.Content.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(kgnerContent_);
                            kgnerContent_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 82: {
                        com.aisera.common.Content.Builder subBuilder = null;
                        if (sentimentContent_ != null) {
                            subBuilder = sentimentContent_.toBuilder();
                        }
                        sentimentContent_ = input.readMessage(com.aisera.common.Content.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(sentimentContent_);
                            sentimentContent_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 88: {

                        sentimentContentCached_ = input.readBool();
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                quads_ = java.util.Collections.unmodifiableList(quads_);
            }
            if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                entities_ = java.util.Collections.unmodifiableList(entities_);
            }
            if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                nodes_ = java.util.Collections.unmodifiableList(nodes_);
            }
            makeExtensionsImmutable();
        }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.aisera.common.MessageDefs.internal_static_Question_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.aisera.common.MessageDefs.internal_static_Question_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.aisera.common.Question.class, com.aisera.common.Question.Builder.class);
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    private volatile java.lang.Object text_;
    /**
     * <code>string text = 1;</code>
     */
    public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            text_ = s;
            return s;
        }
    }
    /**
     * <code>string text = 1;</code>
     */
    public com.google.protobuf.ByteString
    getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            text_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int QUADS_FIELD_NUMBER = 2;
    private java.util.List<com.aisera.common.Quad> quads_;
    /**
     * <code>repeated .Quad quads = 2;</code>
     */
    public java.util.List<com.aisera.common.Quad> getQuadsList() {
        return quads_;
    }
    /**
     * <code>repeated .Quad quads = 2;</code>
     */
    public java.util.List<? extends com.aisera.common.QuadOrBuilder>
    getQuadsOrBuilderList() {
        return quads_;
    }
    /**
     * <code>repeated .Quad quads = 2;</code>
     */
    public int getQuadsCount() {
        return quads_.size();
    }
    /**
     * <code>repeated .Quad quads = 2;</code>
     */
    public com.aisera.common.Quad getQuads(int index) {
        return quads_.get(index);
    }
    /**
     * <code>repeated .Quad quads = 2;</code>
     */
    public com.aisera.common.QuadOrBuilder getQuadsOrBuilder(
            int index) {
        return quads_.get(index);
    }

    public static final int SENTENCE_FIELD_NUMBER = 3;
    private com.aisera.common.Sentence sentence_;
    /**
     * <code>.Sentence sentence = 3;</code>
     */
    public boolean hasSentence() {
        return sentence_ != null;
    }
    /**
     * <code>.Sentence sentence = 3;</code>
     */
    public com.aisera.common.Sentence getSentence() {
        return sentence_ == null ? com.aisera.common.Sentence.getDefaultInstance() : sentence_;
    }
    /**
     * <code>.Sentence sentence = 3;</code>
     */
    public com.aisera.common.SentenceOrBuilder getSentenceOrBuilder() {
        return getSentence();
    }

    public static final int ORIGINALTEXT_FIELD_NUMBER = 4;
    private volatile java.lang.Object originalText_;
    /**
     * <code>string originalText = 4;</code>
     */
    public java.lang.String getOriginalText() {
        java.lang.Object ref = originalText_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            originalText_ = s;
            return s;
        }
    }
    /**
     * <code>string originalText = 4;</code>
     */
    public com.google.protobuf.ByteString
    getOriginalTextBytes() {
        java.lang.Object ref = originalText_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            originalText_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ENTITIES_FIELD_NUMBER = 5;
    private java.util.List<com.aisera.common.KGEntity> entities_;
    /**
     * <code>repeated .KGEntity entities = 5;</code>
     */
    public java.util.List<com.aisera.common.KGEntity> getEntitiesList() {
        return entities_;
    }
    /**
     * <code>repeated .KGEntity entities = 5;</code>
     */
    public java.util.List<? extends com.aisera.common.KGEntityOrBuilder>
    getEntitiesOrBuilderList() {
        return entities_;
    }
    /**
     * <code>repeated .KGEntity entities = 5;</code>
     */
    public int getEntitiesCount() {
        return entities_.size();
    }
    /**
     * <code>repeated .KGEntity entities = 5;</code>
     */
    public com.aisera.common.KGEntity getEntities(int index) {
        return entities_.get(index);
    }
    /**
     * <code>repeated .KGEntity entities = 5;</code>
     */
    public com.aisera.common.KGEntityOrBuilder getEntitiesOrBuilder(
            int index) {
        return entities_.get(index);
    }

    public static final int ASSETDESC_FIELD_NUMBER = 6;
    private volatile java.lang.Object assetDesc_;
    /**
     * <code>string assetDesc = 6;</code>
     */
    public java.lang.String getAssetDesc() {
        java.lang.Object ref = assetDesc_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            assetDesc_ = s;
            return s;
        }
    }
    /**
     * <code>string assetDesc = 6;</code>
     */
    public com.google.protobuf.ByteString
    getAssetDescBytes() {
        java.lang.Object ref = assetDesc_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            assetDesc_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int SPELLCHECKEDTEXT_FIELD_NUMBER = 7;
    private volatile java.lang.Object spellCheckedText_;
    /**
     * <code>string spellCheckedText = 7;</code>
     */
    public java.lang.String getSpellCheckedText() {
        java.lang.Object ref = spellCheckedText_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            spellCheckedText_ = s;
            return s;
        }
    }
    /**
     * <code>string spellCheckedText = 7;</code>
     */
    public com.google.protobuf.ByteString
    getSpellCheckedTextBytes() {
        java.lang.Object ref = spellCheckedText_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            spellCheckedText_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int NODES_FIELD_NUMBER = 8;
    private java.util.List<com.aisera.common.KGNode> nodes_;
    /**
     * <code>repeated .KGNode nodes = 8;</code>
     */
    public java.util.List<com.aisera.common.KGNode> getNodesList() {
        return nodes_;
    }
    /**
     * <code>repeated .KGNode nodes = 8;</code>
     */
    public java.util.List<? extends com.aisera.common.KGNodeOrBuilder>
    getNodesOrBuilderList() {
        return nodes_;
    }
    /**
     * <code>repeated .KGNode nodes = 8;</code>
     */
    public int getNodesCount() {
        return nodes_.size();
    }
    /**
     * <code>repeated .KGNode nodes = 8;</code>
     */
    public com.aisera.common.KGNode getNodes(int index) {
        return nodes_.get(index);
    }
    /**
     * <code>repeated .KGNode nodes = 8;</code>
     */
    public com.aisera.common.KGNodeOrBuilder getNodesOrBuilder(
            int index) {
        return nodes_.get(index);
    }

    public static final int KGNERCONTENT_FIELD_NUMBER = 9;
    private com.aisera.common.Content kgnerContent_;
    /**
     * <pre>
     * save each content model result separately for caching between conversation-v2 and search
     * </pre>
     *
     * <code>.Content kgnerContent = 9;</code>
     */
    public boolean hasKgnerContent() {
        return kgnerContent_ != null;
    }
    /**
     * <pre>
     * save each content model result separately for caching between conversation-v2 and search
     * </pre>
     *
     * <code>.Content kgnerContent = 9;</code>
     */
    public com.aisera.common.Content getKgnerContent() {
        return kgnerContent_ == null ? com.aisera.common.Content.getDefaultInstance() : kgnerContent_;
    }
    /**
     * <pre>
     * save each content model result separately for caching between conversation-v2 and search
     * </pre>
     *
     * <code>.Content kgnerContent = 9;</code>
     */
    public com.aisera.common.ContentOrBuilder getKgnerContentOrBuilder() {
        return getKgnerContent();
    }

    public static final int SENTIMENTCONTENT_FIELD_NUMBER = 10;
    private com.aisera.common.Content sentimentContent_;
    /**
     * <pre>
     *holds Sentiment Response Content
     * </pre>
     *
     * <code>.Content sentimentContent = 10;</code>
     */
    public boolean hasSentimentContent() {
        return sentimentContent_ != null;
    }
    /**
     * <pre>
     *holds Sentiment Response Content
     * </pre>
     *
     * <code>.Content sentimentContent = 10;</code>
     */
    public com.aisera.common.Content getSentimentContent() {
        return sentimentContent_ == null ? com.aisera.common.Content.getDefaultInstance() : sentimentContent_;
    }
    /**
     * <pre>
     *holds Sentiment Response Content
     * </pre>
     *
     * <code>.Content sentimentContent = 10;</code>
     */
    public com.aisera.common.ContentOrBuilder getSentimentContentOrBuilder() {
        return getSentimentContent();
    }

    public static final int SENTIMENTCONTENTCACHED_FIELD_NUMBER = 11;
    private boolean sentimentContentCached_;
    /**
     * <pre>
     *set to true if SentimentResponse is cached
     * </pre>
     *
     * <code>bool sentimentContentCached = 11;</code>
     */
    public boolean getSentimentContentCached() {
        return sentimentContentCached_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getTextBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
        }
        for (int i = 0; i < quads_.size(); i++) {
            output.writeMessage(2, quads_.get(i));
        }
        if (sentence_ != null) {
            output.writeMessage(3, getSentence());
        }
        if (!getOriginalTextBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, originalText_);
        }
        for (int i = 0; i < entities_.size(); i++) {
            output.writeMessage(5, entities_.get(i));
        }
        if (!getAssetDescBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 6, assetDesc_);
        }
        if (!getSpellCheckedTextBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 7, spellCheckedText_);
        }
        for (int i = 0; i < nodes_.size(); i++) {
            output.writeMessage(8, nodes_.get(i));
        }
        if (kgnerContent_ != null) {
            output.writeMessage(9, getKgnerContent());
        }
        if (sentimentContent_ != null) {
            output.writeMessage(10, getSentimentContent());
        }
        if (sentimentContentCached_ != false) {
            output.writeBool(11, sentimentContentCached_);
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getTextBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
        }
        for (int i = 0; i < quads_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, quads_.get(i));
        }
        if (sentence_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(3, getSentence());
        }
        if (!getOriginalTextBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, originalText_);
        }
        for (int i = 0; i < entities_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(5, entities_.get(i));
        }
        if (!getAssetDescBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, assetDesc_);
        }
        if (!getSpellCheckedTextBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, spellCheckedText_);
        }
        for (int i = 0; i < nodes_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(8, nodes_.get(i));
        }
        if (kgnerContent_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(9, getKgnerContent());
        }
        if (sentimentContent_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(10, getSentimentContent());
        }
        if (sentimentContentCached_ != false) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBoolSize(11, sentimentContentCached_);
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.aisera.common.Question)) {
            return super.equals(obj);
        }
        com.aisera.common.Question other = (com.aisera.common.Question) obj;

        boolean result = true;
        result = result && getText()
                .equals(other.getText());
        result = result && getQuadsList()
                .equals(other.getQuadsList());
        result = result && (hasSentence() == other.hasSentence());
        if (hasSentence()) {
            result = result && getSentence()
                    .equals(other.getSentence());
        }
        result = result && getOriginalText()
                .equals(other.getOriginalText());
        result = result && getEntitiesList()
                .equals(other.getEntitiesList());
        result = result && getAssetDesc()
                .equals(other.getAssetDesc());
        result = result && getSpellCheckedText()
                .equals(other.getSpellCheckedText());
        result = result && getNodesList()
                .equals(other.getNodesList());
        result = result && (hasKgnerContent() == other.hasKgnerContent());
        if (hasKgnerContent()) {
            result = result && getKgnerContent()
                    .equals(other.getKgnerContent());
        }
        result = result && (hasSentimentContent() == other.hasSentimentContent());
        if (hasSentimentContent()) {
            result = result && getSentimentContent()
                    .equals(other.getSentimentContent());
        }
        result = result && (getSentimentContentCached()
                == other.getSentimentContentCached());
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
        if (getQuadsCount() > 0) {
            hash = (37 * hash) + QUADS_FIELD_NUMBER;
            hash = (53 * hash) + getQuadsList().hashCode();
        }
        if (hasSentence()) {
            hash = (37 * hash) + SENTENCE_FIELD_NUMBER;
            hash = (53 * hash) + getSentence().hashCode();
        }
        hash = (37 * hash) + ORIGINALTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getOriginalText().hashCode();
        if (getEntitiesCount() > 0) {
            hash = (37 * hash) + ENTITIES_FIELD_NUMBER;
            hash = (53 * hash) + getEntitiesList().hashCode();
        }
        hash = (37 * hash) + ASSETDESC_FIELD_NUMBER;
        hash = (53 * hash) + getAssetDesc().hashCode();
        hash = (37 * hash) + SPELLCHECKEDTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getSpellCheckedText().hashCode();
        if (getNodesCount() > 0) {
            hash = (37 * hash) + NODES_FIELD_NUMBER;
            hash = (53 * hash) + getNodesList().hashCode();
        }
        if (hasKgnerContent()) {
            hash = (37 * hash) + KGNERCONTENT_FIELD_NUMBER;
            hash = (53 * hash) + getKgnerContent().hashCode();
        }
        if (hasSentimentContent()) {
            hash = (37 * hash) + SENTIMENTCONTENT_FIELD_NUMBER;
            hash = (53 * hash) + getSentimentContent().hashCode();
        }
        hash = (37 * hash) + SENTIMENTCONTENTCACHED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getSentimentContentCached());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.aisera.common.Question parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static com.aisera.common.Question parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aisera.common.Question parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static com.aisera.common.Question parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aisera.common.Question parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static com.aisera.common.Question parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aisera.common.Question parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }
    public static com.aisera.common.Question parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aisera.common.Question parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aisera.common.Question parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aisera.common.Question parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }
    public static com.aisera.common.Question parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aisera.common.Question prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }
    /**
     * Protobuf type {@code Question}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Question)
            com.aisera.common.QuestionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.aisera.common.MessageDefs.internal_static_Question_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.aisera.common.MessageDefs.internal_static_Question_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.aisera.common.Question.class, com.aisera.common.Question.Builder.class);
        }

        // Construct using com.aisera.common.Question.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getQuadsFieldBuilder();
                getEntitiesFieldBuilder();
                getNodesFieldBuilder();
            }
        }
        public Builder clear() {
            super.clear();
            text_ = "";

            if (quadsBuilder_ == null) {
                quads_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
            } else {
                quadsBuilder_.clear();
            }
            if (sentenceBuilder_ == null) {
                sentence_ = null;
            } else {
                sentence_ = null;
                sentenceBuilder_ = null;
            }
            originalText_ = "";

            if (entitiesBuilder_ == null) {
                entities_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000010);
            } else {
                entitiesBuilder_.clear();
            }
            assetDesc_ = "";

            spellCheckedText_ = "";

            if (nodesBuilder_ == null) {
                nodes_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000080);
            } else {
                nodesBuilder_.clear();
            }
            if (kgnerContentBuilder_ == null) {
                kgnerContent_ = null;
            } else {
                kgnerContent_ = null;
                kgnerContentBuilder_ = null;
            }
            if (sentimentContentBuilder_ == null) {
                sentimentContent_ = null;
            } else {
                sentimentContent_ = null;
                sentimentContentBuilder_ = null;
            }
            sentimentContentCached_ = false;

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.aisera.common.MessageDefs.internal_static_Question_descriptor;
        }

        public com.aisera.common.Question getDefaultInstanceForType() {
            return com.aisera.common.Question.getDefaultInstance();
        }

        public com.aisera.common.Question build() {
            com.aisera.common.Question result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public com.aisera.common.Question buildPartial() {
            com.aisera.common.Question result = new com.aisera.common.Question(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.text_ = text_;
            if (quadsBuilder_ == null) {
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    quads_ = java.util.Collections.unmodifiableList(quads_);
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.quads_ = quads_;
            } else {
                result.quads_ = quadsBuilder_.build();
            }
            if (sentenceBuilder_ == null) {
                result.sentence_ = sentence_;
            } else {
                result.sentence_ = sentenceBuilder_.build();
            }
            result.originalText_ = originalText_;
            if (entitiesBuilder_ == null) {
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                    entities_ = java.util.Collections.unmodifiableList(entities_);
                    bitField0_ = (bitField0_ & ~0x00000010);
                }
                result.entities_ = entities_;
            } else {
                result.entities_ = entitiesBuilder_.build();
            }
            result.assetDesc_ = assetDesc_;
            result.spellCheckedText_ = spellCheckedText_;
            if (nodesBuilder_ == null) {
                if (((bitField0_ & 0x00000080) == 0x00000080)) {
                    nodes_ = java.util.Collections.unmodifiableList(nodes_);
                    bitField0_ = (bitField0_ & ~0x00000080);
                }
                result.nodes_ = nodes_;
            } else {
                result.nodes_ = nodesBuilder_.build();
            }
            if (kgnerContentBuilder_ == null) {
                result.kgnerContent_ = kgnerContent_;
            } else {
                result.kgnerContent_ = kgnerContentBuilder_.build();
            }
            if (sentimentContentBuilder_ == null) {
                result.sentimentContent_ = sentimentContent_;
            } else {
                result.sentimentContent_ = sentimentContentBuilder_.build();
            }
            result.sentimentContentCached_ = sentimentContentCached_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.aisera.common.Question) {
                return mergeFrom((com.aisera.common.Question)other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.aisera.common.Question other) {
            if (other == com.aisera.common.Question.getDefaultInstance()) return this;
            if (!other.getText().isEmpty()) {
                text_ = other.text_;
                onChanged();
            }
            if (quadsBuilder_ == null) {
                if (!other.quads_.isEmpty()) {
                    if (quads_.isEmpty()) {
                        quads_ = other.quads_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensureQuadsIsMutable();
                        quads_.addAll(other.quads_);
                    }
                    onChanged();
                }
            } else {
                if (!other.quads_.isEmpty()) {
                    if (quadsBuilder_.isEmpty()) {
                        quadsBuilder_.dispose();
                        quadsBuilder_ = null;
                        quads_ = other.quads_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                        quadsBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getQuadsFieldBuilder() : null;
                    } else {
                        quadsBuilder_.addAllMessages(other.quads_);
                    }
                }
            }
            if (other.hasSentence()) {
                mergeSentence(other.getSentence());
            }
            if (!other.getOriginalText().isEmpty()) {
                originalText_ = other.originalText_;
                onChanged();
            }
            if (entitiesBuilder_ == null) {
                if (!other.entities_.isEmpty()) {
                    if (entities_.isEmpty()) {
                        entities_ = other.entities_;
                        bitField0_ = (bitField0_ & ~0x00000010);
                    } else {
                        ensureEntitiesIsMutable();
                        entities_.addAll(other.entities_);
                    }
                    onChanged();
                }
            } else {
                if (!other.entities_.isEmpty()) {
                    if (entitiesBuilder_.isEmpty()) {
                        entitiesBuilder_.dispose();
                        entitiesBuilder_ = null;
                        entities_ = other.entities_;
                        bitField0_ = (bitField0_ & ~0x00000010);
                        entitiesBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getEntitiesFieldBuilder() : null;
                    } else {
                        entitiesBuilder_.addAllMessages(other.entities_);
                    }
                }
            }
            if (!other.getAssetDesc().isEmpty()) {
                assetDesc_ = other.assetDesc_;
                onChanged();
            }
            if (!other.getSpellCheckedText().isEmpty()) {
                spellCheckedText_ = other.spellCheckedText_;
                onChanged();
            }
            if (nodesBuilder_ == null) {
                if (!other.nodes_.isEmpty()) {
                    if (nodes_.isEmpty()) {
                        nodes_ = other.nodes_;
                        bitField0_ = (bitField0_ & ~0x00000080);
                    } else {
                        ensureNodesIsMutable();
                        nodes_.addAll(other.nodes_);
                    }
                    onChanged();
                }
            } else {
                if (!other.nodes_.isEmpty()) {
                    if (nodesBuilder_.isEmpty()) {
                        nodesBuilder_.dispose();
                        nodesBuilder_ = null;
                        nodes_ = other.nodes_;
                        bitField0_ = (bitField0_ & ~0x00000080);
                        nodesBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getNodesFieldBuilder() : null;
                    } else {
                        nodesBuilder_.addAllMessages(other.nodes_);
                    }
                }
            }
            if (other.hasKgnerContent()) {
                mergeKgnerContent(other.getKgnerContent());
            }
            if (other.hasSentimentContent()) {
                mergeSentimentContent(other.getSentimentContent());
            }
            if (other.getSentimentContentCached() != false) {
                setSentimentContentCached(other.getSentimentContentCached());
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            com.aisera.common.Question parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.aisera.common.Question) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }
        private int bitField0_;

        private java.lang.Object text_ = "";
        /**
         * <code>string text = 1;</code>
         */
        public java.lang.String getText() {
            java.lang.Object ref = text_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                text_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        /**
         * <code>string text = 1;</code>
         */
        public com.google.protobuf.ByteString
        getTextBytes() {
            java.lang.Object ref = text_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                text_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <code>string text = 1;</code>
         */
        public Builder setText(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            text_ = value;
            onChanged();
            return this;
        }
        /**
         * <code>string text = 1;</code>
         */
        public Builder clearText() {

            text_ = getDefaultInstance().getText();
            onChanged();
            return this;
        }
        /**
         * <code>string text = 1;</code>
         */
        public Builder setTextBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            text_ = value;
            onChanged();
            return this;
        }

        private java.util.List<com.aisera.common.Quad> quads_ =
                java.util.Collections.emptyList();
        private void ensureQuadsIsMutable() {
            if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                quads_ = new java.util.ArrayList<com.aisera.common.Quad>(quads_);
                bitField0_ |= 0x00000002;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.aisera.common.Quad, com.aisera.common.Quad.Builder, com.aisera.common.QuadOrBuilder> quadsBuilder_;

        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public java.util.List<com.aisera.common.Quad> getQuadsList() {
            if (quadsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(quads_);
            } else {
                return quadsBuilder_.getMessageList();
            }
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public int getQuadsCount() {
            if (quadsBuilder_ == null) {
                return quads_.size();
            } else {
                return quadsBuilder_.getCount();
            }
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public com.aisera.common.Quad getQuads(int index) {
            if (quadsBuilder_ == null) {
                return quads_.get(index);
            } else {
                return quadsBuilder_.getMessage(index);
            }
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public Builder setQuads(
                int index, com.aisera.common.Quad value) {
            if (quadsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureQuadsIsMutable();
                quads_.set(index, value);
                onChanged();
            } else {
                quadsBuilder_.setMessage(index, value);
            }
            return this;
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public Builder setQuads(
                int index, com.aisera.common.Quad.Builder builderForValue) {
            if (quadsBuilder_ == null) {
                ensureQuadsIsMutable();
                quads_.set(index, builderForValue.build());
                onChanged();
            } else {
                quadsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public Builder addQuads(com.aisera.common.Quad value) {
            if (quadsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureQuadsIsMutable();
                quads_.add(value);
                onChanged();
            } else {
                quadsBuilder_.addMessage(value);
            }
            return this;
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public Builder addQuads(
                int index, com.aisera.common.Quad value) {
            if (quadsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureQuadsIsMutable();
                quads_.add(index, value);
                onChanged();
            } else {
                quadsBuilder_.addMessage(index, value);
            }
            return this;
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public Builder addQuads(
                com.aisera.common.Quad.Builder builderForValue) {
            if (quadsBuilder_ == null) {
                ensureQuadsIsMutable();
                quads_.add(builderForValue.build());
                onChanged();
            } else {
                quadsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public Builder addQuads(
                int index, com.aisera.common.Quad.Builder builderForValue) {
            if (quadsBuilder_ == null) {
                ensureQuadsIsMutable();
                quads_.add(index, builderForValue.build());
                onChanged();
            } else {
                quadsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public Builder addAllQuads(
                java.lang.Iterable<? extends com.aisera.common.Quad> values) {
            if (quadsBuilder_ == null) {
                ensureQuadsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, quads_);
                onChanged();
            } else {
                quadsBuilder_.addAllMessages(values);
            }
            return this;
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public Builder clearQuads() {
            if (quadsBuilder_ == null) {
                quads_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
            } else {
                quadsBuilder_.clear();
            }
            return this;
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public Builder removeQuads(int index) {
            if (quadsBuilder_ == null) {
                ensureQuadsIsMutable();
                quads_.remove(index);
                onChanged();
            } else {
                quadsBuilder_.remove(index);
            }
            return this;
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public com.aisera.common.Quad.Builder getQuadsBuilder(
                int index) {
            return getQuadsFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public com.aisera.common.QuadOrBuilder getQuadsOrBuilder(
                int index) {
            if (quadsBuilder_ == null) {
                return quads_.get(index);  } else {
                return quadsBuilder_.getMessageOrBuilder(index);
            }
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public java.util.List<? extends com.aisera.common.QuadOrBuilder>
        getQuadsOrBuilderList() {
            if (quadsBuilder_ != null) {
                return quadsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(quads_);
            }
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public com.aisera.common.Quad.Builder addQuadsBuilder() {
            return getQuadsFieldBuilder().addBuilder(
                    com.aisera.common.Quad.getDefaultInstance());
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public com.aisera.common.Quad.Builder addQuadsBuilder(
                int index) {
            return getQuadsFieldBuilder().addBuilder(
                    index, com.aisera.common.Quad.getDefaultInstance());
        }
        /**
         * <code>repeated .Quad quads = 2;</code>
         */
        public java.util.List<com.aisera.common.Quad.Builder>
        getQuadsBuilderList() {
            return getQuadsFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.aisera.common.Quad, com.aisera.common.Quad.Builder, com.aisera.common.QuadOrBuilder>
        getQuadsFieldBuilder() {
            if (quadsBuilder_ == null) {
                quadsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        com.aisera.common.Quad, com.aisera.common.Quad.Builder, com.aisera.common.QuadOrBuilder>(
                        quads_,
                        ((bitField0_ & 0x00000002) == 0x00000002),
                        getParentForChildren(),
                        isClean());
                quads_ = null;
            }
            return quadsBuilder_;
        }

        private com.aisera.common.Sentence sentence_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                com.aisera.common.Sentence, com.aisera.common.Sentence.Builder, com.aisera.common.SentenceOrBuilder> sentenceBuilder_;
        /**
         * <code>.Sentence sentence = 3;</code>
         */
        public boolean hasSentence() {
            return sentenceBuilder_ != null || sentence_ != null;
        }
        /**
         * <code>.Sentence sentence = 3;</code>
         */
        public com.aisera.common.Sentence getSentence() {
            if (sentenceBuilder_ == null) {
                return sentence_ == null ? com.aisera.common.Sentence.getDefaultInstance() : sentence_;
            } else {
                return sentenceBuilder_.getMessage();
            }
        }
        /**
         * <code>.Sentence sentence = 3;</code>
         */
        public Builder setSentence(com.aisera.common.Sentence value) {
            if (sentenceBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                sentence_ = value;
                onChanged();
            } else {
                sentenceBuilder_.setMessage(value);
            }

            return this;
        }
        /**
         * <code>.Sentence sentence = 3;</code>
         */
        public Builder setSentence(
                com.aisera.common.Sentence.Builder builderForValue) {
            if (sentenceBuilder_ == null) {
                sentence_ = builderForValue.build();
                onChanged();
            } else {
                sentenceBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }
        /**
         * <code>.Sentence sentence = 3;</code>
         */
        public Builder mergeSentence(com.aisera.common.Sentence value) {
            if (sentenceBuilder_ == null) {
                if (sentence_ != null) {
                    sentence_ =
                            com.aisera.common.Sentence.newBuilder(sentence_).mergeFrom(value).buildPartial();
                } else {
                    sentence_ = value;
                }
                onChanged();
            } else {
                sentenceBuilder_.mergeFrom(value);
            }

            return this;
        }
        /**
         * <code>.Sentence sentence = 3;</code>
         */
        public Builder clearSentence() {
            if (sentenceBuilder_ == null) {
                sentence_ = null;
                onChanged();
            } else {
                sentence_ = null;
                sentenceBuilder_ = null;
            }

            return this;
        }
        /**
         * <code>.Sentence sentence = 3;</code>
         */
        public com.aisera.common.Sentence.Builder getSentenceBuilder() {

            onChanged();
            return getSentenceFieldBuilder().getBuilder();
        }
        /**
         * <code>.Sentence sentence = 3;</code>
         */
        public com.aisera.common.SentenceOrBuilder getSentenceOrBuilder() {
            if (sentenceBuilder_ != null) {
                return sentenceBuilder_.getMessageOrBuilder();
            } else {
                return sentence_ == null ?
                        com.aisera.common.Sentence.getDefaultInstance() : sentence_;
            }
        }
        /**
         * <code>.Sentence sentence = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                com.aisera.common.Sentence, com.aisera.common.Sentence.Builder, com.aisera.common.SentenceOrBuilder>
        getSentenceFieldBuilder() {
            if (sentenceBuilder_ == null) {
                sentenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        com.aisera.common.Sentence, com.aisera.common.Sentence.Builder, com.aisera.common.SentenceOrBuilder>(
                        getSentence(),
                        getParentForChildren(),
                        isClean());
                sentence_ = null;
            }
            return sentenceBuilder_;
        }

        private java.lang.Object originalText_ = "";
        /**
         * <code>string originalText = 4;</code>
         */
        public java.lang.String getOriginalText() {
            java.lang.Object ref = originalText_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                originalText_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        /**
         * <code>string originalText = 4;</code>
         */
        public com.google.protobuf.ByteString
        getOriginalTextBytes() {
            java.lang.Object ref = originalText_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                originalText_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <code>string originalText = 4;</code>
         */
        public Builder setOriginalText(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            originalText_ = value;
            onChanged();
            return this;
        }
        /**
         * <code>string originalText = 4;</code>
         */
        public Builder clearOriginalText() {

            originalText_ = getDefaultInstance().getOriginalText();
            onChanged();
            return this;
        }
        /**
         * <code>string originalText = 4;</code>
         */
        public Builder setOriginalTextBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            originalText_ = value;
            onChanged();
            return this;
        }

        private java.util.List<com.aisera.common.KGEntity> entities_ =
                java.util.Collections.emptyList();
        private void ensureEntitiesIsMutable() {
            if (!((bitField0_ & 0x00000010) == 0x00000010)) {
                entities_ = new java.util.ArrayList<com.aisera.common.KGEntity>(entities_);
                bitField0_ |= 0x00000010;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.aisera.common.KGEntity, com.aisera.common.KGEntity.Builder, com.aisera.common.KGEntityOrBuilder> entitiesBuilder_;

        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public java.util.List<com.aisera.common.KGEntity> getEntitiesList() {
            if (entitiesBuilder_ == null) {
                return java.util.Collections.unmodifiableList(entities_);
            } else {
                return entitiesBuilder_.getMessageList();
            }
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public int getEntitiesCount() {
            if (entitiesBuilder_ == null) {
                return entities_.size();
            } else {
                return entitiesBuilder_.getCount();
            }
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public com.aisera.common.KGEntity getEntities(int index) {
            if (entitiesBuilder_ == null) {
                return entities_.get(index);
            } else {
                return entitiesBuilder_.getMessage(index);
            }
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public Builder setEntities(
                int index, com.aisera.common.KGEntity value) {
            if (entitiesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureEntitiesIsMutable();
                entities_.set(index, value);
                onChanged();
            } else {
                entitiesBuilder_.setMessage(index, value);
            }
            return this;
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public Builder setEntities(
                int index, com.aisera.common.KGEntity.Builder builderForValue) {
            if (entitiesBuilder_ == null) {
                ensureEntitiesIsMutable();
                entities_.set(index, builderForValue.build());
                onChanged();
            } else {
                entitiesBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public Builder addEntities(com.aisera.common.KGEntity value) {
            if (entitiesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureEntitiesIsMutable();
                entities_.add(value);
                onChanged();
            } else {
                entitiesBuilder_.addMessage(value);
            }
            return this;
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public Builder addEntities(
                int index, com.aisera.common.KGEntity value) {
            if (entitiesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureEntitiesIsMutable();
                entities_.add(index, value);
                onChanged();
            } else {
                entitiesBuilder_.addMessage(index, value);
            }
            return this;
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public Builder addEntities(
                com.aisera.common.KGEntity.Builder builderForValue) {
            if (entitiesBuilder_ == null) {
                ensureEntitiesIsMutable();
                entities_.add(builderForValue.build());
                onChanged();
            } else {
                entitiesBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public Builder addEntities(
                int index, com.aisera.common.KGEntity.Builder builderForValue) {
            if (entitiesBuilder_ == null) {
                ensureEntitiesIsMutable();
                entities_.add(index, builderForValue.build());
                onChanged();
            } else {
                entitiesBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public Builder addAllEntities(
                java.lang.Iterable<? extends com.aisera.common.KGEntity> values) {
            if (entitiesBuilder_ == null) {
                ensureEntitiesIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, entities_);
                onChanged();
            } else {
                entitiesBuilder_.addAllMessages(values);
            }
            return this;
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public Builder clearEntities() {
            if (entitiesBuilder_ == null) {
                entities_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000010);
                onChanged();
            } else {
                entitiesBuilder_.clear();
            }
            return this;
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public Builder removeEntities(int index) {
            if (entitiesBuilder_ == null) {
                ensureEntitiesIsMutable();
                entities_.remove(index);
                onChanged();
            } else {
                entitiesBuilder_.remove(index);
            }
            return this;
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public com.aisera.common.KGEntity.Builder getEntitiesBuilder(
                int index) {
            return getEntitiesFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public com.aisera.common.KGEntityOrBuilder getEntitiesOrBuilder(
                int index) {
            if (entitiesBuilder_ == null) {
                return entities_.get(index);  } else {
                return entitiesBuilder_.getMessageOrBuilder(index);
            }
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public java.util.List<? extends com.aisera.common.KGEntityOrBuilder>
        getEntitiesOrBuilderList() {
            if (entitiesBuilder_ != null) {
                return entitiesBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(entities_);
            }
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public com.aisera.common.KGEntity.Builder addEntitiesBuilder() {
            return getEntitiesFieldBuilder().addBuilder(
                    com.aisera.common.KGEntity.getDefaultInstance());
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public com.aisera.common.KGEntity.Builder addEntitiesBuilder(
                int index) {
            return getEntitiesFieldBuilder().addBuilder(
                    index, com.aisera.common.KGEntity.getDefaultInstance());
        }
        /**
         * <code>repeated .KGEntity entities = 5;</code>
         */
        public java.util.List<com.aisera.common.KGEntity.Builder>
        getEntitiesBuilderList() {
            return getEntitiesFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.aisera.common.KGEntity, com.aisera.common.KGEntity.Builder, com.aisera.common.KGEntityOrBuilder>
        getEntitiesFieldBuilder() {
            if (entitiesBuilder_ == null) {
                entitiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        com.aisera.common.KGEntity, com.aisera.common.KGEntity.Builder, com.aisera.common.KGEntityOrBuilder>(
                        entities_,
                        ((bitField0_ & 0x00000010) == 0x00000010),
                        getParentForChildren(),
                        isClean());
                entities_ = null;
            }
            return entitiesBuilder_;
        }

        private java.lang.Object assetDesc_ = "";
        /**
         * <code>string assetDesc = 6;</code>
         */
        public java.lang.String getAssetDesc() {
            java.lang.Object ref = assetDesc_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                assetDesc_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        /**
         * <code>string assetDesc = 6;</code>
         */
        public com.google.protobuf.ByteString
        getAssetDescBytes() {
            java.lang.Object ref = assetDesc_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                assetDesc_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <code>string assetDesc = 6;</code>
         */
        public Builder setAssetDesc(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            assetDesc_ = value;
            onChanged();
            return this;
        }
        /**
         * <code>string assetDesc = 6;</code>
         */
        public Builder clearAssetDesc() {

            assetDesc_ = getDefaultInstance().getAssetDesc();
            onChanged();
            return this;
        }
        /**
         * <code>string assetDesc = 6;</code>
         */
        public Builder setAssetDescBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            assetDesc_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object spellCheckedText_ = "";
        /**
         * <code>string spellCheckedText = 7;</code>
         */
        public java.lang.String getSpellCheckedText() {
            java.lang.Object ref = spellCheckedText_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                spellCheckedText_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        /**
         * <code>string spellCheckedText = 7;</code>
         */
        public com.google.protobuf.ByteString
        getSpellCheckedTextBytes() {
            java.lang.Object ref = spellCheckedText_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                spellCheckedText_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <code>string spellCheckedText = 7;</code>
         */
        public Builder setSpellCheckedText(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            spellCheckedText_ = value;
            onChanged();
            return this;
        }
        /**
         * <code>string spellCheckedText = 7;</code>
         */
        public Builder clearSpellCheckedText() {

            spellCheckedText_ = getDefaultInstance().getSpellCheckedText();
            onChanged();
            return this;
        }
        /**
         * <code>string spellCheckedText = 7;</code>
         */
        public Builder setSpellCheckedTextBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            spellCheckedText_ = value;
            onChanged();
            return this;
        }

        private java.util.List<com.aisera.common.KGNode> nodes_ =
                java.util.Collections.emptyList();
        private void ensureNodesIsMutable() {
            if (!((bitField0_ & 0x00000080) == 0x00000080)) {
                nodes_ = new java.util.ArrayList<com.aisera.common.KGNode>(nodes_);
                bitField0_ |= 0x00000080;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.aisera.common.KGNode, com.aisera.common.KGNode.Builder, com.aisera.common.KGNodeOrBuilder> nodesBuilder_;

        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public java.util.List<com.aisera.common.KGNode> getNodesList() {
            if (nodesBuilder_ == null) {
                return java.util.Collections.unmodifiableList(nodes_);
            } else {
                return nodesBuilder_.getMessageList();
            }
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public int getNodesCount() {
            if (nodesBuilder_ == null) {
                return nodes_.size();
            } else {
                return nodesBuilder_.getCount();
            }
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public com.aisera.common.KGNode getNodes(int index) {
            if (nodesBuilder_ == null) {
                return nodes_.get(index);
            } else {
                return nodesBuilder_.getMessage(index);
            }
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public Builder setNodes(
                int index, com.aisera.common.KGNode value) {
            if (nodesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureNodesIsMutable();
                nodes_.set(index, value);
                onChanged();
            } else {
                nodesBuilder_.setMessage(index, value);
            }
            return this;
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public Builder setNodes(
                int index, com.aisera.common.KGNode.Builder builderForValue) {
            if (nodesBuilder_ == null) {
                ensureNodesIsMutable();
                nodes_.set(index, builderForValue.build());
                onChanged();
            } else {
                nodesBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public Builder addNodes(com.aisera.common.KGNode value) {
            if (nodesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureNodesIsMutable();
                nodes_.add(value);
                onChanged();
            } else {
                nodesBuilder_.addMessage(value);
            }
            return this;
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public Builder addNodes(
                int index, com.aisera.common.KGNode value) {
            if (nodesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureNodesIsMutable();
                nodes_.add(index, value);
                onChanged();
            } else {
                nodesBuilder_.addMessage(index, value);
            }
            return this;
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public Builder addNodes(
                com.aisera.common.KGNode.Builder builderForValue) {
            if (nodesBuilder_ == null) {
                ensureNodesIsMutable();
                nodes_.add(builderForValue.build());
                onChanged();
            } else {
                nodesBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public Builder addNodes(
                int index, com.aisera.common.KGNode.Builder builderForValue) {
            if (nodesBuilder_ == null) {
                ensureNodesIsMutable();
                nodes_.add(index, builderForValue.build());
                onChanged();
            } else {
                nodesBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public Builder addAllNodes(
                java.lang.Iterable<? extends com.aisera.common.KGNode> values) {
            if (nodesBuilder_ == null) {
                ensureNodesIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, nodes_);
                onChanged();
            } else {
                nodesBuilder_.addAllMessages(values);
            }
            return this;
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public Builder clearNodes() {
            if (nodesBuilder_ == null) {
                nodes_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000080);
                onChanged();
            } else {
                nodesBuilder_.clear();
            }
            return this;
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public Builder removeNodes(int index) {
            if (nodesBuilder_ == null) {
                ensureNodesIsMutable();
                nodes_.remove(index);
                onChanged();
            } else {
                nodesBuilder_.remove(index);
            }
            return this;
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public com.aisera.common.KGNode.Builder getNodesBuilder(
                int index) {
            return getNodesFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public com.aisera.common.KGNodeOrBuilder getNodesOrBuilder(
                int index) {
            if (nodesBuilder_ == null) {
                return nodes_.get(index);  } else {
                return nodesBuilder_.getMessageOrBuilder(index);
            }
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public java.util.List<? extends com.aisera.common.KGNodeOrBuilder>
        getNodesOrBuilderList() {
            if (nodesBuilder_ != null) {
                return nodesBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(nodes_);
            }
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public com.aisera.common.KGNode.Builder addNodesBuilder() {
            return getNodesFieldBuilder().addBuilder(
                    com.aisera.common.KGNode.getDefaultInstance());
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public com.aisera.common.KGNode.Builder addNodesBuilder(
                int index) {
            return getNodesFieldBuilder().addBuilder(
                    index, com.aisera.common.KGNode.getDefaultInstance());
        }
        /**
         * <code>repeated .KGNode nodes = 8;</code>
         */
        public java.util.List<com.aisera.common.KGNode.Builder>
        getNodesBuilderList() {
            return getNodesFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.aisera.common.KGNode, com.aisera.common.KGNode.Builder, com.aisera.common.KGNodeOrBuilder>
        getNodesFieldBuilder() {
            if (nodesBuilder_ == null) {
                nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        com.aisera.common.KGNode, com.aisera.common.KGNode.Builder, com.aisera.common.KGNodeOrBuilder>(
                        nodes_,
                        ((bitField0_ & 0x00000080) == 0x00000080),
                        getParentForChildren(),
                        isClean());
                nodes_ = null;
            }
            return nodesBuilder_;
        }

        private com.aisera.common.Content kgnerContent_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                com.aisera.common.Content, com.aisera.common.Content.Builder, com.aisera.common.ContentOrBuilder> kgnerContentBuilder_;
        /**
         * <pre>
         * save each content model result separately for caching between conversation-v2 and search
         * </pre>
         *
         * <code>.Content kgnerContent = 9;</code>
         */
        public boolean hasKgnerContent() {
            return kgnerContentBuilder_ != null || kgnerContent_ != null;
        }
        /**
         * <pre>
         * save each content model result separately for caching between conversation-v2 and search
         * </pre>
         *
         * <code>.Content kgnerContent = 9;</code>
         */
        public com.aisera.common.Content getKgnerContent() {
            if (kgnerContentBuilder_ == null) {
                return kgnerContent_ == null ? com.aisera.common.Content.getDefaultInstance() : kgnerContent_;
            } else {
                return kgnerContentBuilder_.getMessage();
            }
        }
        /**
         * <pre>
         * save each content model result separately for caching between conversation-v2 and search
         * </pre>
         *
         * <code>.Content kgnerContent = 9;</code>
         */
        public Builder setKgnerContent(com.aisera.common.Content value) {
            if (kgnerContentBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                kgnerContent_ = value;
                onChanged();
            } else {
                kgnerContentBuilder_.setMessage(value);
            }

            return this;
        }
        /**
         * <pre>
         * save each content model result separately for caching between conversation-v2 and search
         * </pre>
         *
         * <code>.Content kgnerContent = 9;</code>
         */
        public Builder setKgnerContent(
                com.aisera.common.Content.Builder builderForValue) {
            if (kgnerContentBuilder_ == null) {
                kgnerContent_ = builderForValue.build();
                onChanged();
            } else {
                kgnerContentBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }
        /**
         * <pre>
         * save each content model result separately for caching between conversation-v2 and search
         * </pre>
         *
         * <code>.Content kgnerContent = 9;</code>
         */
        public Builder mergeKgnerContent(com.aisera.common.Content value) {
            if (kgnerContentBuilder_ == null) {
                if (kgnerContent_ != null) {
                    kgnerContent_ =
                            com.aisera.common.Content.newBuilder(kgnerContent_).mergeFrom(value).buildPartial();
                } else {
                    kgnerContent_ = value;
                }
                onChanged();
            } else {
                kgnerContentBuilder_.mergeFrom(value);
            }

            return this;
        }
        /**
         * <pre>
         * save each content model result separately for caching between conversation-v2 and search
         * </pre>
         *
         * <code>.Content kgnerContent = 9;</code>
         */
        public Builder clearKgnerContent() {
            if (kgnerContentBuilder_ == null) {
                kgnerContent_ = null;
                onChanged();
            } else {
                kgnerContent_ = null;
                kgnerContentBuilder_ = null;
            }

            return this;
        }
        /**
         * <pre>
         * save each content model result separately for caching between conversation-v2 and search
         * </pre>
         *
         * <code>.Content kgnerContent = 9;</code>
         */
        public com.aisera.common.Content.Builder getKgnerContentBuilder() {

            onChanged();
            return getKgnerContentFieldBuilder().getBuilder();
        }
        /**
         * <pre>
         * save each content model result separately for caching between conversation-v2 and search
         * </pre>
         *
         * <code>.Content kgnerContent = 9;</code>
         */
        public com.aisera.common.ContentOrBuilder getKgnerContentOrBuilder() {
            if (kgnerContentBuilder_ != null) {
                return kgnerContentBuilder_.getMessageOrBuilder();
            } else {
                return kgnerContent_ == null ?
                        com.aisera.common.Content.getDefaultInstance() : kgnerContent_;
            }
        }
        /**
         * <pre>
         * save each content model result separately for caching between conversation-v2 and search
         * </pre>
         *
         * <code>.Content kgnerContent = 9;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                com.aisera.common.Content, com.aisera.common.Content.Builder, com.aisera.common.ContentOrBuilder>
        getKgnerContentFieldBuilder() {
            if (kgnerContentBuilder_ == null) {
                kgnerContentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        com.aisera.common.Content, com.aisera.common.Content.Builder, com.aisera.common.ContentOrBuilder>(
                        getKgnerContent(),
                        getParentForChildren(),
                        isClean());
                kgnerContent_ = null;
            }
            return kgnerContentBuilder_;
        }

        private com.aisera.common.Content sentimentContent_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                com.aisera.common.Content, com.aisera.common.Content.Builder, com.aisera.common.ContentOrBuilder> sentimentContentBuilder_;
        /**
         * <pre>
         *holds Sentiment Response Content
         * </pre>
         *
         * <code>.Content sentimentContent = 10;</code>
         */
        public boolean hasSentimentContent() {
            return sentimentContentBuilder_ != null || sentimentContent_ != null;
        }
        /**
         * <pre>
         *holds Sentiment Response Content
         * </pre>
         *
         * <code>.Content sentimentContent = 10;</code>
         */
        public com.aisera.common.Content getSentimentContent() {
            if (sentimentContentBuilder_ == null) {
                return sentimentContent_ == null ? com.aisera.common.Content.getDefaultInstance() : sentimentContent_;
            } else {
                return sentimentContentBuilder_.getMessage();
            }
        }
        /**
         * <pre>
         *holds Sentiment Response Content
         * </pre>
         *
         * <code>.Content sentimentContent = 10;</code>
         */
        public Builder setSentimentContent(com.aisera.common.Content value) {
            if (sentimentContentBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                sentimentContent_ = value;
                onChanged();
            } else {
                sentimentContentBuilder_.setMessage(value);
            }

            return this;
        }
        /**
         * <pre>
         *holds Sentiment Response Content
         * </pre>
         *
         * <code>.Content sentimentContent = 10;</code>
         */
        public Builder setSentimentContent(
                com.aisera.common.Content.Builder builderForValue) {
            if (sentimentContentBuilder_ == null) {
                sentimentContent_ = builderForValue.build();
                onChanged();
            } else {
                sentimentContentBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }
        /**
         * <pre>
         *holds Sentiment Response Content
         * </pre>
         *
         * <code>.Content sentimentContent = 10;</code>
         */
        public Builder mergeSentimentContent(com.aisera.common.Content value) {
            if (sentimentContentBuilder_ == null) {
                if (sentimentContent_ != null) {
                    sentimentContent_ =
                            com.aisera.common.Content.newBuilder(sentimentContent_).mergeFrom(value).buildPartial();
                } else {
                    sentimentContent_ = value;
                }
                onChanged();
            } else {
                sentimentContentBuilder_.mergeFrom(value);
            }

            return this;
        }
        /**
         * <pre>
         *holds Sentiment Response Content
         * </pre>
         *
         * <code>.Content sentimentContent = 10;</code>
         */
        public Builder clearSentimentContent() {
            if (sentimentContentBuilder_ == null) {
                sentimentContent_ = null;
                onChanged();
            } else {
                sentimentContent_ = null;
                sentimentContentBuilder_ = null;
            }

            return this;
        }
        /**
         * <pre>
         *holds Sentiment Response Content
         * </pre>
         *
         * <code>.Content sentimentContent = 10;</code>
         */
        public com.aisera.common.Content.Builder getSentimentContentBuilder() {

            onChanged();
            return getSentimentContentFieldBuilder().getBuilder();
        }
        /**
         * <pre>
         *holds Sentiment Response Content
         * </pre>
         *
         * <code>.Content sentimentContent = 10;</code>
         */
        public com.aisera.common.ContentOrBuilder getSentimentContentOrBuilder() {
            if (sentimentContentBuilder_ != null) {
                return sentimentContentBuilder_.getMessageOrBuilder();
            } else {
                return sentimentContent_ == null ?
                        com.aisera.common.Content.getDefaultInstance() : sentimentContent_;
            }
        }
        /**
         * <pre>
         *holds Sentiment Response Content
         * </pre>
         *
         * <code>.Content sentimentContent = 10;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                com.aisera.common.Content, com.aisera.common.Content.Builder, com.aisera.common.ContentOrBuilder>
        getSentimentContentFieldBuilder() {
            if (sentimentContentBuilder_ == null) {
                sentimentContentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        com.aisera.common.Content, com.aisera.common.Content.Builder, com.aisera.common.ContentOrBuilder>(
                        getSentimentContent(),
                        getParentForChildren(),
                        isClean());
                sentimentContent_ = null;
            }
            return sentimentContentBuilder_;
        }

        private boolean sentimentContentCached_ ;
        /**
         * <pre>
         *set to true if SentimentResponse is cached
         * </pre>
         *
         * <code>bool sentimentContentCached = 11;</code>
         */
        public boolean getSentimentContentCached() {
            return sentimentContentCached_;
        }
        /**
         * <pre>
         *set to true if SentimentResponse is cached
         * </pre>
         *
         * <code>bool sentimentContentCached = 11;</code>
         */
        public Builder setSentimentContentCached(boolean value) {

            sentimentContentCached_ = value;
            onChanged();
            return this;
        }
        /**
         * <pre>
         *set to true if SentimentResponse is cached
         * </pre>
         *
         * <code>bool sentimentContentCached = 11;</code>
         */
        public Builder clearSentimentContentCached() {

            sentimentContentCached_ = false;
            onChanged();
            return this;
        }
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope:Question)
    }

    // @@protoc_insertion_point(class_scope:Question)
    private static final com.aisera.common.Question DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new com.aisera.common.Question();
    }

    public static com.aisera.common.Question getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Question>
            PARSER = new com.google.protobuf.AbstractParser<Question>() {
        public Question parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Question(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<Question> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Question> getParserForType() {
        return PARSER;
    }

    public com.aisera.common.Question getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

