package com.company.common;

public enum SearchType {
  MATCH_ALL,
  MATCH_TERM,
  MATCH_PHRASE,

  //PHRASE_IN_SUBJECT,
  BIGRAM_IN_SUBJECT,
  SPAN_IN_SUBJECT,
  SPAN_IN_CONTENT,
  SPAN_IN_SUBJECT_AND_CONTENT,
  SPAN_IN_HIERARCHICAL_SUBJECT,
  BIGRAM_IN_HIERARCHICAL_SUBJECT,
  KEYWORD_IN_TITLE,
  EXTERNAL_KB_ID,
  INTENT,
  ENTITY,
  ENTITY_IN_SUBJECT,
  ENTITY_IN_HIERARCHICAL_SUBJECT,
  ENTITY_IN_CONTENT,
  ENTITY_IN_TITLE,
  INTENT_ENTITY,
  FULLTEXT_KEYWORD,
  FULLTEXT_PHRASE,
  KEYWORD_IN_SUBJECT,
  KEYWORD_IN_HIERARCHICAL_SUBJECT,
  KEYWORD_IN_CONTENT,
  INTENT_ENTITY_IN_OVERRIDE,
  INTENT_OVERRIDE,
  SYNONYM,
  NONE
}
